apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv-auth-deployment
spec:
  selector:
    matchLabels:
      app: srv-auth
  replicas: 2 # Adjust the number of replicas as needed
  template:
    metadata:
      labels:
        app: srv-auth
    spec:
      containers:
      - name: srv-auth
        image: aton85/srv-auth-image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8060
---
apiVersion: v1
kind: Service
metadata:
  name: srv-auth-service
spec:
  selector:
    app: srv-auth
  ports:
  - protocol: "TCP"
    port: 8060
    targetPort: 8060
  type: LoadBalancer
